name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v1
      - run: zig run ./src/main.zig
      - run: rustup default stable
      - run: cargo update
      - run: cargo install --locked cargo-zigbuild,
      - run: cargo zigbuild --release
